### ISSUE TITLE
support RNA in complement

### ISSUE THREAD

**Issue by posativ** [sonwell/biotools#1]
Hi,

currently when I make the complement of an RNA containing Uracil, every U is translated to an N. That makes no sense. I've seen the `type=nucl|prot` maybe it can either autodect RNA or add a new type.

**Comment by sonwell** [comment]
I've not assigned a new type in the case of RNA, instead complement will just make sure that there are 'U's and no 'T's or vice-versa and will complement accordingly.

**Comment by posativ** [comment]
Great, thanks!
