### ISSUE TITLE
performance and memory usage of Sequence (and fasta)

### ISSUE THREAD

**Issue by posativ** [sonwell/biotools#2]
Hi there,

I currently do some researches on the newly released musa cuminata (banana) genome. Unfortunately `biotools` is very inefficient in handling a 469 megabyte fasta file (takes ~12 seconds to load it from disk). Somehow python can not handle this huge amount of memory properly, so when I move the sequence pointers to a dictionary, it pauses for about a second or so. Every additional operation like `__getitem__` takes also very long.

I think that lazy reading would be better for this kind of task … (I currently do some tests in my fork).

**Comment by sonwell** [comment]
The latest no longer does .upper() after a fasta sequence is read, and determining whether a sequence is protein or not has been deferred to when seq.type is actually used.

This drops the runtime from ~25 seconds to ~7 seconds on my machine, but a few things depended on the upper-case-ness of the sequence, so something may have broken (I hope I got most of them, though).

**Comment by posativ** [comment]
Next time, you should use `@property` for this lazy stuff ;-) In my fork I used a runtime heuristic, feel free to merge this [1]. Thanks for the speed optimization anyways!

1: https://github.com/posativ/biotools/blob/dbe758ba4d2204a415cd51c156344ab748e9b735/src/sequence.py
