### ISSUE TITLE
Please fix Python3 issues

### ISSUE THREAD

**Issue by tillea** [sonwell/biotools#6]
Hi,
when creating a Debian package I noticed that there are some relicts from Python 2 which fail when using with Python3.  I have created a [patch](https://anonscm.debian.org/cgit/debian-med/python-biotools.git/tree/debian/patches/2to3.patch) for a potential Debian package which you can feel free to take over.
Kind regards, Andreas.

**Comment by sonwell** [comment]
I have applied your patch.

**Comment by tillea** [comment]
Thanks for your very quick response.  Here is [another patch](https://anonscm.debian.org/cgit/debian-med/python-biotools.git/tree/debian/patches/2to3_grepseq.patch) covering grepseq.
